import {Injectable} from '@angular/core';

@Injectable()
export class LinpCardsModelService {

  constructor() {
  }

  getCards() {
const enCards = [
  'plastic', 'camera', 'game', 'night', 'thief', 'lipstick', 'share', 'ointment', 'wart', 'cliff', 'whip', 'London',
  'winter', 'fall', 'gardener', 'bean', 'lion', 'corridor', 'power plant', 'pan', 'hose', 'quarter', 'box',
  'glasses', 'goose', 'cinema', 'gang', 'key', 'group', 'harbor', 'comrade', 'jump', 'kick', 'hurricane', 'tongue', 'Paris', 'wind',
  'microphone', 'man', 'mug', 'alcohol', 'stairs', 'country', 'nature', 'lungs', 'crane', 'steel', 'Egypt', 'shore', 'sport',
  'flour', 'New Year\'s Eve', 'dance', 'rocket', 'speaker', 'terrine', 'dust', 'lens', 'wound', 'paragraph',
  'market', 'ananas', 'child', 'clock', 'salt', 'garden', 'Manchester', 'tear', 'mane', 'prayer', 'sack', 'court',
  'earth', 'note', 'flag', 'nail', 'donkey', 'scales',' New York ',' rose ',' portrait ',' bullet ',' sleep ',' Australia ',' beach ',
  'player ',' farmer ',' Christmas', 'cock', 'roof', 'president', 'tool', 'gravel', 'lance', 'Jerusalem',
  'sun', 'princess',' butcher ',' bread ',' dog ',' button ',' camping ',' seal ',' coffin ',' comb ',' back ',' shirt ',' forest' ,
  'radio', 'chalk', 'pot', 'sugar', 'house', 'engineer', 'tennis', 'gold', 'guitar', 'sister', 'citizen', 'gas', 'studs', 
  'blossom', 'fist', 'dagger', 'breast', 'Europe', 'cave', 'paper', 'belly', 'half', 'sting', 'skateboard', 'castle', 'pudding',
  'vacuum cleaner', 'mattress', 'wardrobe', 'river', 'coast', 'ball', 'tractor', 'calendar', 'hair', 'dragon', 'professor', 'wave', 
  'semester', 'groin', 'tooth', 'Vienna', 'Ice', 'song', 'pencil', 'certificate', 'bowl', 'horse', 'altar', 'berry', 'beard', 
  'automat', 'bone', 'Berlin', 'wool', 'God', 'spoon', 'boss', 'blanket', 'bat', 'oncle', 'ski', 'ditch', 'meat', 'Baghdad', 
  'church', 'plate', 'soldier', 'morning', 'cat', 'mast', 'repairman', 'sock', 'eyelash', 'model', 'finger', 'Rome',
  'coal', 'drum', 'aunt', 'grain', 'door', 'Edinburgh', 'herring', 'body', 'raft', 'cushion', 'France', 'water', 'set',
   'rifle', 'evening', 'zoo', 'boat', 'human', 'knitting', 'cell', 'skid', 'egg', 'heath','weather', 'football', 'library',
  'soup', 'bear', 'Sidney', 'shower', 'calculator', 'gondola', 'single', 'pyramid', 'disc', 'angel', 'slip', 'staple',
  'coffee', 'channel', 'board', 'bull', 'paddle', 'flake', 'heart', 'Bankok', 'sea', 'knight', 'plan', 'fruit', 'cow', 'cellar',
  'chamber', 'halftime', 'sieve', 'third', 'head', 'thread', 'voice ',' teacher ',' plug ',' fruit ',' road ',' Equator ',
  ' bee ',' break ',' bomb ',' tail ',' Munich ', 'field', 'city', 'secretary', 'work', 'hoof', 'shelf', 'author', 'swing', 'ink', 
  'camp', 'bubble', 'Tokyo', 'wood', 'organ', 'woman', 'day', 'cook', 'sail', 'plumber', 'knife', 'push', 'tornado', 'virgin',
  'Istanbul', 'volcano', 'trumpet', 'carpenter', 'noon', 'feed', 'lamp', 'mixer', 'shot', 'whirlpool', 'bullet', 'paint', 'east',
  'autumn', 'tower', 'oven', 'cheese', 'fly', 'terrace', 'magazine', 'pedal', 'stone', 'ocean', 'net', 'Arctic', 'desert', 'flute',
  'glove', 'blackboard', 'core', 'carriage', 'Peru', 'Bordeaux', 'spring', 'projector', 'step', 'Athens','fire', 'violin', 'doll',
  'hammer', 'elephant', 'flower', 'theater', 'hippo', 'neck', 'Teheran', 'pants', 'shield', 'driver', 'candle', 'scissors',
  'eye', 'skyline', 'strength', 'mud', 'scam', 'rabbit', 'mouse', 'cassette', 'baker', 'sausage', 'lamb', 'leg', 'tank',
  'perfume', 'square', 'memory', 'rubber', 'Stockholm', 'willow', 'movie', 'runner', 'tong', 'snake', 'ship', 'Oslo', 'safari', 
  'forehead', 'law', 'silk', 'Manhattan', 'hat', 'piano', 'mother', 'circle', 'candy', 'car', 'Delhi', 'frog', 'brain', 'dip', 'hand',
  'source', 'dress', 'crown', 'inventor', 'porridge', 'fish', 'bath', 'skyscraper', 'plaster', 'burger', 'cart', 
  'handcuff', 'seam', 'tree', 'cross', 'uncle', 'cup', 'master', 'balcony', 'Dublin', 'tentacle', 'sofa', 'fax',
  'latte', 'Greece', 'mountain', 'TV', 'apartment', 'brush', 'skin', 'nurse', 'jogging', 'screw', 
  'copper', 'goat', 'north', 'rock', 'bed', 'pattern', 'chain', 'milk', 'floor', 'duke', 'ostrich', 'sand', 'storm', 
  'flame', 'Moscow', 'lawn', 'collar', 'tie', 'time', 'paw', 'window', 'hooligan', 'piece', 'call', 'air', 'ear',
  'heaven', 'queen', 'arm', 'hour', 'smile', 'room', 'playboy', 'caravan', 'bag', 'cutter', 'cloth', 'Prague',
  'Jungle', 'ink', 'class', 'pig', 'tent', 'column', 'cutlet', 'date', 'batman',
  'Moon', 'sword', 'foam', 'cake', 'office', 'monument', 'studio', 'desk', 'can', 'dash', 'bundle',
  'iron', 'photo', 'printer', 'wing', 'throw', 'barn', 'malt', 'sink', 'glass', 'chocolate', 'slide', 'banana',
 'fountain', 'countess', 'sweater', 'cone', 'thunder', 'Peking', 'silver', 'crocodile', 'brother', 'telephone', 'ladder',
  'bus', 'plant', 'leaf', 'udder', 'CD', 'limb', 'America', 'wall', 'cymbals', 'filler', 'chair', 'cocoa', 'train', 'conductor',
  'Cap', 'Inline Skates', 'Steam', 'Fair', 'Belfast',  'valley', 'drink', 'Amsterdam', 'week', 'tiger', 'tire', 'St. Petersburg ',
  ' smoke ',' spaceship ',' robe ',' sex ',' Kremlin ', 'waffle', 'fight', 'idea', 'Brussels', 'cancer', 'tango', 'statue', 
  'coca cola', 'hockey', 'march', 'nose', 'feeling', 'mountains', 'ring', 'hairdresser', 'year', 'bird', 'sky', 'rise', 'cinnamon',
   'rust', 'stick', 'cream', 'watts', 'card', 'instrument', 'student', 'table', 'color', 'path', 'official', 'boa', 'golf', 'bronze',
  'park', 'fork', 'father', 'needle', 'tea', 'libra', 'mark', 'tomato', 'video', 'family', 'month', 'coat', 'goal', 'parade', 'drop',
  'turbine', 'art', 'blood', 'south', 'star', 'emperor', 'Africa', 'potato', 'camel', 'airplane', 'float', 'plush', 'roller', 'planer',
   'velvet', 'shoe', 'lightning', 'painter', 'rider', 'minute', 'kitty', 'sanoe', 'Seattle', 'seed', 'cheek', 'premiere', 'stand', 'west',
  'climate', 'housewife', 'block', 'roast', 'duck', 'jam', 'graffiti', 'snout', 'pipe', 'rake', 'drug', 'Zurich',
  'summer', 'role', 'twin', 'butter', 'flea', 'bicycle', 'club', 'palette', 'hexagon', 'knot', 'pill', 'Madrid',
  'school', 'Image', 'boxer', 'Japan', 'apple', 'race', 'Beatles', 'blouse', 'bowling', 'breeze', 'pope', 'barbecue',
  'power', 'chess', 'mill', 'kettle', 'horn', 'course', 'lawyer', 'powder', 'mouth', 'machine', 'number', 'Asia',
  'metal', 'clay', 'diver', 'gift', 'hero', 'traffic', 'chancellor', 'pear', 'gut', 'brush', 'kiss', 'Lisbon'
];


    const cards = [ 
      'Plastik', 'Kamera', 'Spiel', 'Nacht', 'Dieb', 'Ruder', 'Aktie', 'Salbe', 'Warze', 'Klippe', 'Peitsche', 'Dresden',
      'Winter', 'Stock', 'Gärtner', 'Bohne', 'Löwe', 'Flur', 'Kraftwerk', 'Pfanne', 'Schlauch', 'Viertel', 'Kiste', 'Brille',
      'Stamm', 'Kino', 'Bande', 'Schlüssel', 'Gruppe', 'Hafen', 'Kamerad', 'Sprung', 'Tritt', 'Hurrikan', 'Schlag', 'Köln',
      'Wind', 'Mikrofon', 'Mann', 'Becher', 'Alkohol', 'Treppe', 'Land', 'Natur', 'Lunge', 'Gangway', 'Stahl', 'Ägypten',
      'Feder', 'Bogen', 'Kopie', 'Tasche', 'Wolf', 'Wiese', 'Zar', 'Ostern', 'Stille', 'Konzert', 'Mund', 'San Francisco',
      'Ufer', 'Sport', 'Mehl', 'Silvester', 'Schnabel', 'Rakete', 'Redner', 'Terrine', 'Beil', 'Linse', 'Klappe', 'Absatz',
      'Markt', 'Kasten', 'Kind', 'Uhr', 'Salz', 'Garten', 'Manchester', 'Nelke', 'Mähne', 'Gebet', 'Sack', 'Hof',
      'Erde', 'Note', 'Fahne', 'Nagel', 'Esel', 'Schuppen', 'New York', 'Rose', 'Porträt', 'Geschoß', 'Schlaf', 'Australien',
      'Strand', 'Spieler', 'Bauer', 'Weihnachten', 'Hahn', 'Dach', 'Präsident', 'Werkzeug', 'Kies', 'Lanze', 'Hals', 'Jerusalem',
      'Sonne', 'Prinzessin', 'Schlachter', 'Brot', 'Hund', 'Knopf', 'Camping', 'Plombe', 'Sarg', 'Kamm', 'Rücken', 'Hemd',
      'Wald', 'Radio', 'Kreide', 'Topf', 'Zucker', 'Haus', 'Ingenieur', 'Tatze', 'Tennis', 'Hügel', 'Leder', 'Kairo',
      'Gold', 'Gitarre', 'Schwester', 'Bürger', 'Gas', 'Stollen', 'Blüte', 'Faust', 'Dolch', 'Brust', 'Europa',
      'Höhle', 'Papier', 'Bauch', 'Hälfte', 'Stachel', 'Skateboard', 'Schloss', 'Pudding', 'Staubsauger', 'Matratze', 'Schrank', 'Fluss',
      'Küste', 'Ball', 'Trecker', 'Kalender', 'Haar', 'Drachen', 'Professor', 'Welle', 'Semester', 'Leiste', 'Zahn', 'Wien',
      'Eis', 'Lied', 'Stift', 'Schein', 'Schale', 'Pferd', 'Altar', 'Beere', 'Bart', 'Automat', 'Knochen', 'Berlin',
      'Wolle', 'Gott', 'Löffel', 'Chef', 'Decke', 'Minister', 'Teich', 'Ski', 'Graben', 'Fleisch', 'Bagdad',
      'Kirche', 'Platte', 'Soldat', 'Morgen', 'Kater', 'Mast', 'Mechaniker', 'Strumpf', 'Wimper', 'Modell', 'Finger', 'Hamburg',
      'Kohle', 'Trommel', 'Tante', 'Teller', 'Korn', 'Tür', 'Edinburg', 'Hering', 'Körper', 'Floß', 'Kissen', 'Frankreich',
      'Wasser', 'Satz', 'Gewehr', 'Abend', 'Zoo', 'Boot', 'Mensch', 'Strickzeug', 'Zelle', 'Kufe', 'Ei', 'Heide',
      'Wetter', 'Fußball', 'Bücherei', 'Suppe', 'Bär', 'Wagen', 'Sidney', 'Schauer', 'Rechner', 'Gondel', 'Single', 'Pyramide',
      'Scheibe', 'Engel', 'Zettel', 'Klammer', 'Kaffee', 'Kanal', 'Vorstand', 'Stier', 'Paddel', 'Flocke', 'Herz', 'Bankok',
      'See', 'Ritter', 'Plan', 'Obst', 'Kuh', 'Keller', 'Kammer', 'Halbzeit', 'Sieb', 'Drittel', 'Kopf', 'Faden',
      'Sand', 'Stimme', 'Lehrer', 'Stecker', 'Frucht', 'Straße', 'Äquator', 'Biene', 'Bruch', 'Bombe', 'Schwanz', 'München',
      'Weide', 'Stadt', 'Sekretärin', 'Arbeit', 'Huf', 'Regal', 'Schreiber', 'Wippe', 'Tusche', 'Lager', 'Blase', 'Bremen',
      'Holz', 'Orgel', 'Frau', 'Tag', 'Köchin', 'Segel', 'Klemptner', 'Sense', 'Stoß', 'Tornado', 'Jungfrau', 'Istanbul',
      'Vulkan', 'Trompete', 'Tischler', 'Mittag', 'Futter', 'Lampe', 'Mixer', 'Trieb', 'Wirbel', 'Kugel', 'Lack', 'Osten',
      'Herbst', 'Turm', 'Ofen', 'Käse', 'Fliege', 'Terrasse', 'Magazin', 'Pedal', 'Schotter', 'Kippe', 'Netz', 'Arktis',
      'Wüste', 'Flöte', 'Handschuh', 'Tafel', 'Kern', 'Kutsche', 'Bonn', 'Bordeaux', 'Stürmer', 'Beamer', 'Schritt', 'Athen',
      'Feuer', 'Geige', 'Puppe', 'Hammer', 'Elefant', 'Blume', 'Theater', 'Nilpferd', 'Nacken', 'Gemälde', 'Spitze', 'Teheran',
      'Hose', 'Schild', 'Fahrer', 'Kerze', 'Schere', 'Auge', 'Skyline', 'Stärke', 'Schlamm', 'Masche', 'Schwung', 'Socke',
      'Frühling', 'Kassette', 'Bäcker', 'Wurst', 'Lamm', 'Bein', 'Panzer', 'Parfüm', 'Platz', 'Speicher', 'Gummi', 'Stockholm',
      'Feld', 'Film', 'Läufer', 'Zange', 'Schlange', 'Schiff', 'Oslo', 'Safari', 'Stirn', 'Gesetz', 'Seide', 'Manhattan',
      'Hut', 'Klavier', 'Mutter', 'Kreis', 'Bonbon', 'Auto', 'Delhi', 'Frosch', 'Hirn', 'Einlage', 'Hand', 'Quelle',
      'Kleid', 'Krone', 'Erfinder', 'Brei', 'Fisch', 'Bad', 'Hochhaus', 'Pflaster', 'Projektor', 'Karre', 'Handschelle', 'Naht',
      'Baum', 'Kreuz', 'Onkel', 'Tasse', 'Meister', 'Balkon', 'Dublin', 'Fühler', 'Höcker', 'Fax', 'Latte', 'Griechenland',
      'Berg', 'Fernseher', 'Wohnung', 'Besen', 'Haut', 'Dusche', 'Pfleger', 'Jogging', 'Schraube', 'Kupfer', 'Bock', 'Norden',
      'Stein', 'Bett', 'Muster', 'Kette', 'Milch', 'Boden', 'Herzog', 'Strauß', 'Schorchel', 'Gewitter', 'Flamme', 'Moskau',
      'Rasen', 'Kragen', 'Krawatte', 'Zeit', 'Pfote', 'Fenster', 'Hooligan', 'Stück', 'Ruf', 'Luft', 'Ohr', 'Ozean',
      'Himmel', 'Königin', 'Arm', 'Stunde', 'Krallen', 'Zimmer', 'Playboy', 'Wohnwagen', 'Tüte', 'Kutter', 'Stoff', 'Prag',
      'Urwald', 'Pinsel', 'Tinte', 'Klasse', 'Schwein', 'Zelt', 'Säule', 'Kotelett', 'Termin', 'Moor', 'Schuß', 'Rom',
      'Mond', 'Schwert', 'Schaum', 'Kuchen', 'Maus', 'Büro', 'Denkmal', 'Studio', 'Pult', 'Kanne', 'Strich', 'Bund',
      'Eisen', 'Foto', 'Drucker', 'Brett', 'Flügel', 'Wurf', 'Scheune', 'Malz', 'Spüle', 'Matte', 'Loch', 'Brücke',
      'Glas', 'Schokolade', 'Folie', 'Schüssel', 'Banane', 'Brunnen', 'Gräfin', 'Pullover', 'Kegel', 'Donner', 'Zunge', 'Peking',
      'Silber', 'Taste', 'Bruder', 'Telefon', 'Leiter', 'Bus', 'Anlage', 'Blatt', 'Euter', 'CD', 'Glied', 'Amerika',
      'Mauer', 'Becken', 'Füller', 'Stuhl', 'Kakao', 'Zug', 'Dirigent', 'Kappe', 'Inline-Skates', 'Dampf', 'Messe', 'Belfast',
      'Tal', 'Getränk', 'Sattel', 'Woche', 'Tiger', 'Reifen', 'St. Petersburg', 'Rauch', 'Raumschiff', 'Gewand', 'Sex', 'Kreml',
      'Sturm', 'Kampf', 'Idee', 'Peife', 'Krebs', 'Schaukel', 'Statue', 'Teig', 'Schleife', 'Marsch', 'Nase', 'Filz',
      'Gebirge', 'Ring', 'Frisörin', 'Jahr', 'Vogel', 'Schlitten', 'Schmied', 'Zimt', 'Rost', 'Stab', 'Creme', 'Watt',
      'Karte', 'Instrument', 'Schüler', 'Tisch', 'Farbe', 'Weg', 'Beamter', 'Boa', 'Golf', 'Bronze', 'Liebe', 'Pol',
      'Park', 'Gabel', 'Vater', 'Nadel', 'Tee', 'Waage', 'Mark', 'Eichel', 'Flosse', 'DVD', 'Fessel', 'Afrika',
      'Meer', 'Video', 'Familie', 'Monat', 'Fell', 'Tor', 'Parade', 'Tropfen', 'Turbine', 'Kunst', 'Blut', 'Süden',
      'Stern', 'Kaiser', 'Tuch', 'Kartoffel', 'Kamel', 'Flugzeug', 'Schwimmer', 'Plüsch', 'Roller', 'Hobel', 'Samt', 'Schuh',
      'Blitz', 'Maler', 'Reiter', 'Minute', 'Katze', 'Kanu', 'Seattle', 'Samen', 'Wange', 'Premiere', 'Ständer', 'Westen',
      'Klima', 'Hausfrau', 'Block', 'Braten', 'Ente', 'Stau', 'Graffiti', 'Schnauze', 'Rohr', 'Harke', 'Droge', 'Zürich',
      'Sommer', 'Rolle', 'Zwilling', 'Butter', 'Floh', 'Fahrrad', 'Verein', 'Palette', 'Sechseck', 'Knoten', 'Pille', 'Madrid',
      'Schule', 'Bild', 'Boxer', 'Messer', 'Apfel', 'Wettrennen', 'Beatles', 'Bluse', 'Bowling', 'Brise', 'Papst', 'Burg',
      'Strom', 'Schach', 'Mühle', 'Kessel', 'Horn', 'Bahn', 'Anwalt', 'Pulver', 'Mündung', 'Maschine', 'Nummer', 'Asien',
      'Metall', 'Ton', 'Taucher', 'Niete', 'Held', 'Verkehr', 'Kanzler', 'Birne', 'Darm', 'Bürste', 'Kuss', 'London'
    ];
    return cards;
  }
}
